clang: Fix snprintf warnings.
These warnings are introduced with the addition of Clang 9.0.6 (r365631).

../../../../../../kernel/google/bonito/drivers/input/touchscreen/synaptics_dsx_v27/synaptics_dsx_core.c:3864:3: error: 'snprintf' size argument is too large; destination buffer has size 16, but size argument is 4096 [-Werror,-Wfortify-source]
                snprintf(buf, PAGE_SIZE, "dsx_gpio_%u\n", gpio);
                ^

../../../../../../kernel/google/bonito/techpack/audio/asoc/codecs/wcd_cpe_core.c:1981:2: error: 'snprintf' size argument is too large; destination buffer has size 11, but size argument is 13 [-Werror,-Wfortify-source]
        snprintf(proc_name, (sizeof("cpe") + sizeof("_state") +
        ^

../../../../../../kernel/google/bonito/techpack/audio/asoc/codecs/wsa881x.c:392:9: error: 'snprintf' size argument is too large; destination buffer has size 20, but size argument is 25 [-Werror,-Wfortify-source]
                len = snprintf(tmp_buf, 25, "0x%.3x: 0x%.2x\n", i,
                      ^

Change-Id: Ic5cd69c72976295e26f71bbe8f625969a97d634c